import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import "./styles/globals.css";
import Navbar from "./components/Navbar";
import { Lato } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({
  weight: ["400", "700"], // Example: Include regular and bold weights
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lato.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
